SCREEN_WIDTH = 1300 
SCREEN_HEIGHT = 800
MAX_IMAGE_HEIGHT = int(SCREEN_HEIGHT * 0.5)
MAX_Y_SCALE = 0.8
MIN_Y = 100
Y_STEP = 20
MAX_SPRITE_COUNT = 35

IMAGE_SUFFIXES = {
    ".jpg",
    ".jpeg",
    ".png",
}